bar {
    colors {
        background #000000
        statusline #e3e2e5

        focused_workspace #5c7093 #5c7093 #ffffff

        inactive_workspace #000000 #000000 #c4c6cf

        urgent_workspace #b3c7ee #b3c7ee #334768
    }
	position top
	status_command ~/.config/sway/swaybar.sh
	
	mode dock
	font Terminus 11
	status_edge_padding 0
}
