set $focus_border    #5c7093
set $focus_bg        #5c7093
set $focus_text      #ffffff
set $focus_indicator #b3c7ee

set $unfocus_border    #333333
set $unfocus_bg        #333333
set $unfocus_text      #888888
set $unfocus_indicator #292d2e

client.focused          $focus_border    $focus_bg        $focus_text    $focus_indicator $focus_border
client.unfocused        $unfocus_border  $unfocus_bg      $unfocus_text  $unfocus_indicator $unfocus_border
client.focused_inactive $unfocus_border  $unfocus_bg      $unfocus_text  $unfocus_indicator $unfocus_border
client.urgent        #b3c7ee #b3c7ee #334768 #b3c7ee #b3c7ee
